### ISSUE TITLE
Errors Running Locally

### ISSUE THREAD

**Issue by bitnom** [PeerServer/peer-server#4]
I try to run locally...

`sh coffee.sh` produces some errors:

```
peer-server/client/ClientBrowserDataChannel.coffee:4:11: error: Can't call super with @params in derived class constructors
    super(@onDataCallback)
          ^^^^^^^^^^^^^^^
ClientServerDataChannel.coffee:4:5: error: Can't reference 'this' before calling super in derived class constructors
    @onConnectionCallback = options.onConnectionCallback
    ^
```

if I then try to run `sh server.sh` I get:

```
dev environment detected
util.js:135
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined
    at Object.inherits (util.js:135:11)
    at Object.<anonymous> (/home/t/code/js/peer-server/node_modules/peer/node_modules/restify/node_modules/spdy/lib/spdy/server.js:297:6)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/t/code/js/peer-server/node_modules/peer/node_modules/restify/node_modules/spdy/lib/spdy.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
```

**Comment by meowalien** [comment]
Hi I encountered the same problem in Windows10 WSL2

sudo ./coffee.sh
```
peer-server/client/ClientBrowserDataChannel.coffee:4:11: error: Can't call super with @params in derived class constructors
    super(@onDataCallback)
          ^^^^^^^^^^^^^^^
```

sudo sh ./server.sh
```
dev environment detected
util.js:280
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^
```
